export const IMAGES = {
  MOONER: {
    'mooner-phone': '/images/mooner-phone.svg',
    'mooner-chat': '/images/mooner-chat.png',
    'moonoz-logo': '/images/moonoz-logo.png',
    'moonoz-hello': '/images/moonoz-hello.png',
    MOONER: '/images/mooner-origin.svg',
    MOONER_GAME: '/images/mooner-game.svg',
    MOONER_PRESENT: '/images/mooner-present.svg',
    MOONER_PENCIL: '/images/mooner-pencil.svg',
    'mooner-hotplace': '/images/mooner-hotplace.png',
    'mooner-share': 'https://d3e0ocbonj571p.cloudfront.net/MoonoZ.png',
    rotation_1: 'https://d3e0ocbonj571p.cloudfront.net/Rotation_1.png',
    rotation_2: 'https://d3e0ocbonj571p.cloudfront.net/Rotation_2.png',
    rotation_3: 'https://d3e0ocbonj571p.cloudfront.net/Rotation_3.png',
    rotation_4: 'https://d3e0ocbonj571p.cloudfront.net/Rotation_4.png',
    'mooner-sad': '/images/mooner-sad.svg',
  },
  COUPON: {
    TICKET_RED: '/images/ticket-red.svg',
    TICKET_YELLOW: '/images/ticket-yellow.svg',
    TICKET_GRAY: '/images/ticket-gray.svg',
  },
  TACO: {
    'taco-signal': 'images/taco-signal.png',
    'taco-main-front': 'images/taco-main-front.png',
    'taco-main-back': 'images/taco-main-back.png',
    'taco-pan': 'images/taco-pan.png',
    'taco-sub-back': 'images/taco-sub-back.png',
    'taco-sub-front': 'images/taco-sub-front.png',
    'taco-berry-back': 'images/taco-berry-back.png',
    'taco-berry-front': 'images/taco-berry-front.png',
    'taco-eggy-back': 'images/taco-eggy-back.png',
    'taco-eggy-front': 'images/taco-eggy-front.png',
    'taco-wasab-back': 'images/taco-wasab-back.png',
    'taco-wasab-front': 'images/taco-wasab-front.png',
    'taco-greeny-back': 'images/taco-greeny-back.png',
    'taco-greeny-front': 'images/taco-greeny-front.png',
    'taco-crunch-back': 'images/taco-crunch-back.png',
    'taco-crunch-front': 'images/taco-crunch-front.png',
    'taco-spicy-back': 'images/taco-spicy-back.png',
    'taco-spicy-front': 'images/taco-spicy-front.png',
    'taco-milky-back': 'images/taco-milky-back.png',
    'taco-milky-front': 'images/taco-milky-front.png',
  },
  bubble: '/images/bubble.png',
} as const;
